version: '3'
services:
  web:
    container_name: web
    build: web/
    environment:
      - FLASK_ENV=development
      - PYTHON UNBUFFERED=True
    restart: on-failure
    volumes:
      - ./web:/web
    ports:
      - "5001:5001"
    networks:
      - ngrok_net
      - postgres
      - redis
      - clickhouse
    depends_on:
      - postgres
    command: python3 server.py

  redis:
    container_name: redis
    image: arm32v6/redis:alpine
    restart: always
    entrypoint: redis-server --appendonly yes --requirepass admin --maxmemory 512mb --maxmemory-policy allkeys-lru
    networks:
      - redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data

  postgres:
    container_name: postgres
    image: arm32v6/postgres:alpine
    environment:
      POSTGRES_DB: "library"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_MULTIPLE_EXTENSIONS: "postgis,hstore,postgis_topology,postgis_raster,pgrouting"
      RUN_AS_ROOT: "true"
    volumes:
      - ./postgres/SQL:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: on-failure
    networks:
      - postgres
networks:
  postgres:
    driver: bridge
  ngrok_net:
    driver: bridge
  redis:
    driver: bridge
  clickhouse:
    driver: bridge